### ISSUE TITLE
Frage zum Projekt

### ISSUE THREAD

**Issue by DavidCraftDev** [2020Sanoj/Software-Installer#1]
Lebt dieses Projekt noch?

**Comment by 2020Sanoj** [comment]
Ja nur habe ich noch nichts auf github geschoben, ich verusch morgen eine version zu machen die ich auf github schieben werde

**Comment by 2020Sanoj** [comment]
NEIN ICH WILL

**Comment by DavidCraftDev** [comment]
ICH WILL

**Comment by 2020Sanoj** [comment]
NEIN ICH
